image: docker:stable
variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest

stages:
  - build

build:
  only:
    - master
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE || true
    - docker build --cache-from $CONTAINER_IMAGE -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
