- name: Ensure required system packages
  apt:
    name:
    - software-properties-common
    - python3
    - python3-pip
    - python3-setuptools
    - virtualenv
    state: present
    update_cache: true

- name: Install docker python lib
  pip:
    name:
      - docker
    executable: /usr/bin/pip3
    state: present
  tags:
    - docker
